version: '2'

services:
  apache:
    image: 'bitnami/apache:latest'
    container_name: $NAME
    volumes:
      - .:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code-ta-bd.entrypoints=$ENTRYPOINT"
      - "traefik.http.routers.code-ta-bd.rule=Host(`$DOMAIN`)"
    networks:
      - $NETWORK
    restart: always

networks:
  machinerie-network:
    external:
      name: $NETWORK
